### ISSUE TITLE
Calendar requiring from 'src' directory, breaking npm package

### ISSUE THREAD

**Issue by bmathews** [atsid/react-calendar-render#8]
The compiled output in the `lib` folder ends up pulling in an uncompiled file from `src` because of this, causing a syntax error on the JSX.

https://github.com/atsid/react-calendar-render/blob/master/src/Calendar.js#L4

@davija

**Comment by bleegard** [comment]
Fixed on fork after changed get pulled should be fixed.

**Comment by davija** [comment]
This should be fixed now with the changes bill submitted yesterday that have been merged to master.
